name: KSPDB Production Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into EC2 and Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "🚀 Starting Deployment..."
            
            # Ensure the directory matches your repository name on the EC2 instance
            cd ~/propel-assignment 
            
            echo "📥 Pulling latest code from GitHub..."
            git pull origin main
            
            echo "🐳 Rebuilding and restarting Docker containers..."
            sudo docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d --build
            
            echo "🧹 Cleaning up old Docker images..."
            sudo docker image prune -f
            
            echo "✅ Deployment Successful!"